---
# Substitution variables used through the codebase
substitutions:
  icon_font: mdi_icons_40
  text_font: nunito_20
  text_color: white
  bg_color: black
  button_on_color: "ep_orange"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  # LCD back light modes - Code in backlight_time.yaml
  # Set Day mode - starts at Sunrise - screen at 100%
  touchscreen_daytime_brightness: "100%"
  # Set Evening mode -  starts at Sunset - screen at 50% (may need to be brighter for some screens)
  touchscreen_nighttime_brightness: "65%"
  # Set Night mode start time (default is midnight)
  touchscreen_night_hour: "0"      # Hour for night mode (0-23)
  touchscreen_night_minute: "0"    # Minute for night mode (0-59)
  # Set touchscreen idle timeout - In night mode back light goes off after this amount of time
  touchscreen_idle_timeout: "60s"

esphome:
  name: "waveshare-esp32-s3-touch-28b"
  friendly_name: "Waveshare-2.8-round"

# Enable logging
logger:

packages:
  # Generic configuration for ESP32 screens
  wifi: !include esphome-modular-lvgl-buttons/common/wifi.yaml
  ota_screen: !include esphome-modular-lvgl-buttons/common/ota.yaml
  # All the colors
  colors: !include esphome-modular-lvgl-buttons/common/color.yaml
  # Some nice basic fonts
  fonts: !include esphome-modular-lvgl-buttons/common/fonts.yaml
  # 1000s of glyphs
  glyphs: !include esphome-modular-lvgl-buttons/common/mdi_glyph_substitutions.yaml
  # Some basic sensors
  sensors: !include esphome-modular-lvgl-buttons/sensors/sensors_base.yaml
  # Styles + Themes
  theme_style: !include esphome-modular-lvgl-buttons/common/theme_style.yaml
  # Use this theme for debugging
  # theme_style: !include esphome-modular-lvgl-buttons/common/theme_style_debug.yaml
  # Include if your touch screen has a backlight. Also sets the time from HA

  # Harware description file
  hardware: !include esphome-modular-lvgl-buttons/hardware/waveshare-esp32-s3-touch-lcd-2.8b.yaml
  
  # Basic boot screen with ESPHome logo and device diagnostic info
  loading_screen: !include esphome-modular-lvgl-buttons/pages/loading_480px.yaml
  # info screen - WiFi login, IP address, MAC address etc
  info_screen: !include esphome-modular-lvgl-buttons/pages/info.yaml  

# LVGL Configuration
lvgl:
  buffer_size: 100%
  pages:
    - id: main_page
      widgets:
        - label:
            id: coord_text
            align: CENTER
            text_align: CENTER
            text: 'Touch the screen'

touchscreen:
  - id: !extend my_touchscreen
    on_update:
        - lvgl.label.update:
            id: coord_text
            text: !lambda return str_sprintf("Touch points:\n id=%d x=%d, y=%d", touches[0].id, touches[0].x, touches[0].y);
        - lambda: |-
            for (auto touch: touches)  {
                if (touch.state <= 2) {
                  ESP_LOGI("Touch points:", "id=%d x=%d, y=%d", touch.id, touch.x, touch.y);
                }
            }
